name: Sweep abc-ghac usage

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Target version/ref of abc-ghac (e.g. v3)"
        required: true
        default: "v3"

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Example GH call
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          # Example: list your repos
          gh repo list $GITHUB_ACTOR --json nameWithOwner -L 10
